---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC set up variables
      include_vars: vars/bastion_setup

    - name: Imprt VPC set up variables
      include_vars: vars/output_vars

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file  bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 400
      when: key_out.changed

    # create security group for bastion

    - name: Create Sec Group for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: allow port 22 from anywhere and all ports within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - debug:
        var: BastionSG_out

    # Create Jumpserver ( Bastion Host)
    - name: Creating Bastion Host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes   # wait until this becomes healthy before continuing
        wait_timeout: 600 # maximum we are going to wait for is 300 seconds
        instance_tags:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: Devops Team
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: Devops Team
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out




